import React, { useState, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { scenarios, indiaStates } from '@/data/indiaStates';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

interface ScenarioInputProps {
  onScenarioSubmit?: (scenario: string, affectedStates: string[]) => void;
}

const ScenarioInput: React.FC<ScenarioInputProps> = ({ onScenarioSubmit }) => {
  const [input, setInput] = useState('');
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [showOutput, setShowOutput] = useState(false);
  const [generatedStrategy, setGeneratedStrategy] = useState('');
  const outputRef = useRef<HTMLDivElement>(null);

  const analyzeScenario = async () => {
    if (!input.trim()) return;
    
    setIsAnalyzing(true);
    
    // Simulate analysis delay
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    // Detect affected states from input
    const affectedStates: string[] = [];
    const inputLower = input.toLowerCase();
    
    if (inputLower.includes('maharashtra') || inputLower.includes('marathwada')) {
      affectedStates.push('MH');
    }
    if (inputLower.includes('rajasthan')) {
      affectedStates.push('RJ');
    }
    if (inputLower.includes('karnataka')) {
      affectedStates.push('KA');
    }
    if (inputLower.includes('tamil nadu') || inputLower.includes('tamilnadu')) {
      affectedStates.push('TN');
    }
    if (inputLower.includes('punjab')) {
      affectedStates.push('PB');
    }
    if (inputLower.includes('gujarat')) {
      affectedStates.push('GJ');
    }
    if (inputLower.includes('uttar pradesh') || inputLower.includes('up ')) {
      affectedStates.push('UP');
    }
    if (inputLower.includes('bihar')) {
      affectedStates.push('BR');
    }
    
    if (affectedStates.length === 0) {
      affectedStates.push('MH'); // Default
    }
    
    // Generate strategy based on scenario
    const strategy = generateStrategy(input, affectedStates);
    setGeneratedStrategy(strategy);
    setShowOutput(true);
    
    onScenarioSubmit?.(input, affectedStates);
    setIsAnalyzing(false);
  };

  const generateStrategy = (scenario: string, states: string[]) => {
    const stateNames = states.map(s => indiaStates.find(st => st.id === s)?.name || s).join(', ');
    
    return `
# RESOURCE ALLOCATION STRATEGY
## Generated by MAPPO Multi-Agent System

### Scenario Analysis
**Input:** ${scenario}
**Affected Region(s):** ${stateNames}
**Analysis Timestamp:** ${new Date().toLocaleString()}

---

## IMMEDIATE ACTIONS (Cycles 1-10)

### 1. Emergency Resource Deployment
- **Water:** Activate interstate water sharing agreements with surplus states
- **Power:** Import 500-800 MW from Gujarat and Madhya Pradesh grids
- **Food:** Release 50,000 MT from central buffer stocks

### 2. Drought Mitigation Protocol
- Deploy mobile water treatment units to affected districts
- Activate 150 community water distribution centers
- Implement 30% water rationing in non-essential sectors

### 3. Agricultural Support
- Provide drought-resistant seed varieties to 200,000 farmers
- Waive irrigation electricity charges for 3 months
- Extend crop insurance claim processing

---

## SHORT-TERM STRATEGY (Cycles 11-30)

### Interstate Coordination
| Partner State | Resource | Volume | Terms |
|--------------|----------|--------|-------|
| Gujarat | Power | 600 MW | 6-month agreement |
| Madhya Pradesh | Water | 2.5 TMC | Canal diversion |
| Punjab | Foodgrain | 25,000 MT | Deferred payment |

### Infrastructure Activation
- Resume inter-basin water transfer from Narmada basin
- Activate 12 dormant tube wells in critical zones
- Deploy 50 water tankers for daily supply

---

## LONG-TERM ADAPTATION (Cycles 31-60)

### Strategic Recommendations
1. **Solar Infrastructure Expansion**
   - Install 500 MW solar capacity to reduce thermal water dependency
   - Estimated cost: ₹2,500 Crore
   - Timeline: 18 months

2. **Micro-Irrigation Mandate**
   - 100% drip irrigation coverage in affected districts
   - 75% subsidy for farmer adoption
   - Target: 500,000 hectares

3. **Groundwater Recharge Program**
   - Construct 2,000 check dams
   - Implement rainwater harvesting in all government buildings
   - Artificial recharge: 500 MCM annually

---

## CONFLICT PREVENTION MEASURES

### Anticipated Tensions
- **Karnataka-Tamil Nadu:** Water release disputes (Probability: 85%)
- **Rajasthan-Punjab:** Power grid access conflicts (Probability: 55%)

### Mitigation Actions
1. Pre-emptive Supreme Court petition filing
2. Central mediator deployment before Cycle 45
3. Transparent daily resource allocation reporting

---

## SUCCESS METRICS

| Metric | Target | Timeline |
|--------|--------|----------|
| Water availability | >60% of normal | 30 cycles |
| Power deficit | <15% | 20 cycles |
| Agricultural yield | >70% of normal | 60 cycles |
| Migration risk | <5% population | 45 cycles |

---

## AGENT CONSENSUS

**Rajasthan Agent:** Prioritizes solar + grid connectivity (73% confidence)
**Karnataka Agent:** Negotiates water releases (65% confidence)
**Maharashtra Agent:** Declares emergency + requests transfers (58% confidence)

**System Recommendation:** Implement immediate water-power-food triad with interstate guarantees.

---

*This strategy was generated by the MAPPO Multi-Agent Reinforcement Learning System.*
*For implementation, coordinate with NITI Aayog and respective state disaster management authorities.*
`;
  };

  const handlePrint = async () => {
    if (!outputRef.current) return;
    
    const canvas = await html2canvas(outputRef.current, {
      backgroundColor: '#0a0a0f',
      scale: 2,
    });
    
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
    
    pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
    pdf.save(`MAPPO-Strategy-${new Date().toISOString().split('T')[0]}.pdf`);
  };

  const handlePrintText = () => {
    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>MAPPO Strategy Report</title>
            <style>
              body { font-family: monospace; white-space: pre-wrap; padding: 40px; }
              h1 { color: #00d4ff; }
              h2 { color: #ff6b35; }
              h3 { color: #00ff88; }
              table { border-collapse: collapse; width: 100%; margin: 20px 0; }
              th, td { border: 1px solid #ccc; padding: 8px; text-align: left; }
              th { background: #f0f0f0; }
            </style>
          </head>
          <body>${generatedStrategy.replace(/\n/g, '<br>').replace(/# /g, '<h1>').replace(/## /g, '<h2>').replace(/### /g, '<h3>')}</body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
  };

  return (
    <div className="relative w-full h-full bg-[#0a0a0f] rounded-xl overflow-hidden">
      {/* Grid Background */}
      <div className="absolute inset-0 grid-bg opacity-50" />
      
      {/* Header */}
      <div className="relative z-10 p-4 border-b border-gray-800">
        <h3 className="text-xl font-bold text-white neon-text">Scenario Analyzer</h3>
        <p className="text-sm text-gray-400 mt-1">Describe a situation to generate resource allocation strategy</p>
      </div>

      {/* Content */}
      <div className="relative z-10 p-4 h-[calc(100%-80px)] overflow-auto">
        {/* Input Section */}
        <div className="space-y-4">
          <div>
            <label className="text-sm text-gray-400 mb-2 block">Describe the scenario</label>
            <Textarea
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="e.g., Maharashtra Region is facing severe droughts affecting 15 districts..."
              className="bg-[#12121a] border-gray-700 text-white placeholder:text-gray-600 min-h-[100px]"
            />
          </div>

          {/* Quick Scenarios */}
          <div>
            <label className="text-xs text-gray-500 mb-2 block">QUICK SCENARIOS</label>
            <div className="flex flex-wrap gap-2">
              {scenarios.map(s => (
                <button
                  key={s.id}
                  onClick={() => setInput(s.description)}
                  className="px-3 py-1.5 bg-[#1a1a25] border border-gray-700 rounded-lg text-xs text-gray-400 hover:border-cyan-500 hover:text-cyan-400 transition-colors"
                >
                  {s.name}
                </button>
              ))}
            </div>
          </div>

          {/* Analyze Button */}
          <Button
            onClick={analyzeScenario}
            disabled={isAnalyzing || !input.trim()}
            className="w-full bg-cyan-500 hover:bg-cyan-600 text-black font-semibold"
          >
            {isAnalyzing ? (
              <span className="flex items-center gap-2">
                <motion.div
                  className="w-4 h-4 border-2 border-black border-t-transparent rounded-full"
                  animate={{ rotate: 360 }}
                  transition={{ duration: 1, repeat: Infinity, ease: 'linear' }}
                />
                Analyzing with MAPPO Agents...
              </span>
            ) : (
              'Generate Strategy'
            )}
          </Button>
        </div>

        {/* Output Section */}
        <AnimatePresence>
          {showOutput && (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="mt-6"
            >
              <div className="flex justify-between items-center mb-3">
                <h4 className="text-sm font-semibold text-cyan-400">Generated Strategy</h4>
                <div className="flex gap-2">
                  <Button
                    onClick={handlePrintText}
                    variant="outline"
                    size="sm"
                    className="border-gray-600 text-gray-300 hover:bg-gray-800"
                  >
                    🖨️ Print
                  </Button>
                  <Button
                    onClick={handlePrint}
                    variant="outline"
                    size="sm"
                    className="border-cyan-500 text-cyan-400 hover:bg-cyan-500/10"
                  >
                    📄 Export PDF
                  </Button>
                </div>
              </div>

              <div 
                ref={outputRef}
                className="bg-[#12121a] border border-gray-700 rounded-lg p-4 font-mono text-sm text-gray-300 overflow-auto max-h-[400px]"
              >
                <pre className="whitespace-pre-wrap">{generatedStrategy}</pre>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
};

export default ScenarioInput;
